name: build

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:

jobs:
  test-release:
    strategy:
      matrix:
        include:
          - url: "https://s3-us-west-2.amazonaws.com/minified-archives.webkit.org/mac-sonoma-x86_64%20arm64-release/292348@main.zip"
            os: macos-14
          - url: "https://s3-us-west-2.amazonaws.com/minified-archives.webkit.org/mac-ventura-x86_64%20arm64-release/290733@main.zip"
            os: macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: easy-install/easy-setup@v1
        with:
          url: ${{ matrix.url }}
      - name: test
        run: |
          curl -L -o "jsc.zip" "${{ matrix.url }}"
          unzip -q "jsc.zip" -d jsc-tmp

          mkdir -p jsc/Release

          cp jsc-tmp/Release/jsc jsc/jsc
          cp -r jsc-tmp/Release/JavaScriptCore.framework jsc/JavaScriptCore.framework
          cp run-jsc.sh jsc/run-jsc.sh

          ls -lh jsc

          bash ./jsc/run-jsc.sh ./test.js